Minor updates to make the document better ageing
mirjak/draft-shmoo-online-meeting pull request #20
Opened 2022-10-20 13:32 UTC by mirjak

and add two recent examples from ietf-111 (9 tracks) and ietf 112 (plenary experiment)

2022-10-20 13:32 UTC, mirjak commented on draft-ietf-shmoo-online-meeting.md
> +The evaluation of the respective survey results indicated that this experiment led to reduction in scheduling conflict but also
```suggestion
The evaluation of the respective survey results indicated that this experiment led to reduction in scheduling conflicts but also
```

2022-10-20 13:33 UTC, mirjak commented on draft-ietf-shmoo-online-meeting.md
> +led to drop in plenary attendance, partly due to limited awareness (see [https://www.ietf.org/blog/ietf112-plenary-experiment-evaluation/]).
```suggestion
led to a slight drop in plenary attendance, partly due to limited awareness (see [https://www.ietf.org/blog/ietf112-plenary-experiment-evaluation/]).
```

2022-10-20 13:34 UTC, mirjak commented on draft-ietf-shmoo-online-meeting.md
> +And, different than for in-person meetings,  also utilizing time during the
```suggestion
And, different than for in-person meetings, utilizing time during the
```

2022-10-24 20:22 UTC, martinduke requested changes

2022-10-24 20:22 UTC, martinduke commented on draft-ietf-shmoo-online-meeting.md
> +and the guidelines that have evolved from this experience. The aim of this RFC is to document rough
```suggestion
and the guidelines that have evolved from this experience. The aim of this document is to define rough
```

2022-10-24 20:22 UTC, martinduke commented on draft-ietf-shmoo-online-meeting.md
> +of running fully online meetings. Similar as the IETF has done it for in-person meetings, changes to the organization
```suggestion
of running fully online meetings. Like the procedure for in-person meetings, changes to the organization
```

2022-10-24 20:22 UTC, martinduke commented on draft-ietf-shmoo-online-meeting.md
> +Also, this document does not cover hybrid meetings (meaning meetings that have higher remote participation
```suggestion
Hybrid meetings (meaning meetings that have higher remote participation than onsite participation)
```

2022-10-24 20:22 UTC, martinduke commented on draft-ietf-shmoo-online-meeting.md
> +than onsite participation). Still, some of the experience gained from fully online meetings might also
```suggestion
are out of scope. However, some of the experience gained from fully online meetings might also
```

2022-10-24 20:22 UTC, martinduke commented on draft-ietf-shmoo-online-meeting.md
> +And, different than for in-person meetings, utilizing time during the
```suggestion
Unlike in-person meetings, utilizing time during the
```

2022-10-24 20:22 UTC, martinduke commented on draft-ietf-shmoo-online-meeting.md
> +Respectively, IETF-111 used 9 paralell tracks for some of the session, but also leading to slightly more schedulin conflicts.
```suggestion
Respectively, IETF-111 used 9 parallel tracks for some of the session, but also leading to slightly more scheduling conflicts.
```

2022-10-24 20:24 UTC, merged